config/routes.rb
#coding: utf-8

Mybbs::Application.routes.draw do
  root to: "messages#index"
  get "show" => "messages#show"
  post "post" => "messages#post"
  get "destroy" => "messages#destroy"
  get "test" => "messages#test"
end

app/models/message_log.rb
class MessageLog < ActiveRecord::Base
  attr_accessible :id, :name, :text, :time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
#coding: utf-8

class MessagesController < ApplicationController
  def index
  	redirect_to action: "show"
  end

  def test
    @aaa = "test"





  end

  def show
  	@messages = MessageLog.order("id DESC").limit("10")
  end
  
  def post
#   インスタンス変数に代入
    @current_time = Time.now.to_s
  	@sent_message = params[:sent_message]
#   IDを設定する
#    if MessageLog.nil?
#      messages_id = 1
#    else
#      messages_id = MessageLog.maximum("id") + 1
#    end
     messages_id = MessageLog.count + 1
#   データベースに記録する    
    message_log = MessageLog.new(params[:sent_message])
    message_log.time = @current_time
    message_log.id = messages_id

    message_log.save
  end

  def destroy
  	message_log = MessageLog.find(params[:id])
  	message_log.destroy
  end
end

#####   memo   #####
#def show
#    if page == 1
#      @messages = MessageLog.order("id DESC").limit("10")
#    elsif page == 2
#      @messages = MessageLog.order("id DESC").offset("11").limit("10")
#    end

#    messages_last_id = MessageLog.maximum("id")
#    @messages_new_id = messages_last_id + 1

#  def show_2
#    @messages = MessageLog.order("id DESC").offset("11").limit("10")
#  end

#def post
#  1.  試作
#    count = MessageLog.count
#    if count == 0
#      messages_last_id = 0
#    else
#      messages_last_id = MessageLog.maximum("id")
#    end
#  2.  1のブラッシュアップ
#    if MessageLog.count == 0
#      messages_last_id = 0
#    else
#      messages_last_id = MessageLog.maximum("id")
#    end
#  3.　   失敗
#    if MessageLog.null?
#      message_log.id = 1
#    else
#     message_log.id = MessageLog.find(:all).last([:ID]+1)
#    end
#    message_log.id = @messages_new_id
#  4.　　　3の成功作
#    if MessageLog.nil?
#      messages_last_id = 0
#    else
#      messages_last_id = MessageLog.maximum("id")
#    end
#    @messages_new_id = messages_last_id + 1

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mybbs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/destroy.html.erb
<p>削除しました</p>
<p><%= link_to "戻る", :action => "show" %></p>

app/views/messages/post.html.erb
<html>
<head>
</head>
<body>
<h1>掲示板</h1>
<p>投稿を受け付けました。</p>
<p>名前：<strong><%= @sent_message[:name] %></strong></p>
<p>メッセージ：<strong><%= @sent_message[:text] %></strong></p>
<p>投稿時刻：<strong><%= @current_time %></strong></p>
<p><%= link_to "戻る", :action => "show" %></p>
</body>
</html>

app/views/messages/show.html.erb
<html>
<head>
<title>Guestbook</title>
</head>
<body>

<%= link_to "test", :action => "test", :controller => "messages" %>

<h1>掲示板</h1>
<h2>投稿する</h2>

<%= form_for :sent_message, :url => {:action => "post"} do |f| %>

<p>名前：<%= f.text_field :name, :size => 15 %></p>
<p>メッセージ<%= f.text_field :text, :size => 50 %></p>
<p><%= f.submit "投稿する" %></p>
<% end %>

<h2>メッセージ一覧</h2>
<dl>
<% @messages.each do |entry| %>
  <dt><strong><%=  entry.name %></strong>[ID=<%= entry.id %>] (<%=  entry.time %>)</dt>
  <dd><%=  entry.text %></dd>
<p><%= link_to "削除", :action => "destroy", id: entry.id %></p>

<% end %>
</dl>
</body>
</html>

<%#####   memo   #####%>

<%# <p>new_ID：<%= @messages_new_id ></p>    %>
<%# <p>ID：<%= f.text_field :id, :size => 5 ></p> %>
  <%#= link_to "削除", destroy_path, method: :delete %>
<%#   <p><%= link_to "→1page", :action => "show" ></p>   %>
<%#   <p><%= link_to "→2page", :action => "show_2" ></p>   %>

app/views/messages/test.html.erb
<%= @aaa %>
<%= link_to "show", :action => "show", :controller => "messages" %>